package org.example.timertgbot.TG;

public enum STEP {
    START, ADDING_STAFF, ADDING_CREDIT, CHECK_CONFIRMING, SEARCHING_STAFF, BACK_ADD_CREDIT, CONFIRMING_ADDING, ADDING_REWARD, ADDING_COMPENSATION, STAFF_START, STAFF_START_MENU, REMOVE_STAFF_NAME,
}
